Dev/hemanthk/push dev (#57)

diff --git a/attestation-verifier/Makefile b/attestation-verifier/Makefile
--- a/attestation-verifier/Makefile
+++ b/attestation-verifier/Makefile
@@ -5,7 +5,8 @@ SHELL:=/bin/bash
 BUILDDATE := $(shell TZ=UTC date +%Y-%m-%dT%H:%M:%SZ)
 PROXY_EXISTS := $(shell if [[ "${https_proxy}" || "${http_proxy}" ]]; then echo 1; else echo 0; fi)
 DOCKER_PROXY_FLAGS := ""
-VERSION := $(shell cat VERSION)
+VERSION_SUFFIX              ?= ""
+VERSION                     ?= $(shell cat ./VERSION)$(VERSION_SUFFIX)
 ifeq ($(PROXY_EXISTS),1)
         DOCKER_PROXY_FLAGS = --build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy}
 else
@@ -17,7 +18,7 @@ DOCKER_REGISTRY    ?= 080137407410.dkr.ecr.us-west-2.amazonaws.com
 DOCKER_TARGETS = nats-init init-wait authservice cms hvs tagent aas-manager
 
 DOCKER_IMAGE = debian:bookworm
-CONTAINER_NAME = attestation_verifier_debian
+CONTAINER_NAME = attestation_verifier_debian_build
 CONTAINER_NAME_TEST = attestation_verifier_debian_test
 VERFIER_DIR_NAME = attestation-verifier
 VERIFIER_PATH =   $(shell find $(PWD) -maxdepth 1 -type d -name $(VERFIER_DIR_NAME) -print -quit)
@@ -36,23 +37,6 @@ build:
 	@# Help: Runs build stage in all subprojects
 	echo "---MAKEFILE BUILD---"
 	echo "attestation-verfier build"
-	sudo true  # Prompt for password once
-
-	@if [ "$(shell docker ps -q -f name=$(CONTAINER_NAME))" ]; then \
-		echo "Error: Container '$(CONTAINER_NAME)' is already running."; \
-		exit 1; \
-	else \
-		echo "Starting container '$(CONTAINER_NAME)'..."; \
-		echo '$(SCRIPT_PATH)';\
-		echo '$(VERIFIER_PATH)';\
-		docker run --rm --privileged --name $(CONTAINER_NAME) \
-			-e http_proxy=${http_proxy} -e https_proxy=${https_proxy} -e VERSION=${VERSION} \
-			-v /var/run/docker.sock:/var/run/docker.sock -v ${VERIFIER_PATH}:/intel_isecl \
-			-v $(SCRIPT_PATH):/attestation_verifier_inside_container.sh \
-			-d $(DOCKER_IMAGE) /attestation_verifier_inside_container.sh build; \
-		docker logs -f $(CONTAINER_NAME); \
-		docker images; \
-	fi
 	echo "---END MAKEFILE Build---"
 
 
@@ -94,7 +78,23 @@ list:
 
 docker-build:
 	@echo "---Docker Build---"
-	echo "add docker build -f Dockerfile -t <image name version> --no-cache <folder"
+	sudo true  # Prompt for password once
+
+	@if [ "$(shell docker ps -q -f name=$(CONTAINER_NAME))" ]; then \
+		echo "Error: Container '$(CONTAINER_NAME)' is already running."; \
+		exit 1; \
+	else \
+		echo "Starting container '$(CONTAINER_NAME)'..."; \
+		echo '$(SCRIPT_PATH)';\
+		echo '$(VERIFIER_PATH)';\
+		docker run --rm --privileged --name $(CONTAINER_NAME) \
+			-e http_proxy=${http_proxy} -e https_proxy=${https_proxy} -e VERSION=${VERSION} \
+			-v /var/run/docker.sock:/var/run/docker.sock -v ${VERIFIER_PATH}:/intel_isecl \
+			-v $(SCRIPT_PATH):/attestation_verifier_inside_container.sh \
+			-d $(DOCKER_IMAGE) /attestation_verifier_inside_container.sh build; \
+		docker logs -f $(CONTAINER_NAME); \
+		docker images; \
+	fi
 	@echo "---End Docker Build---"
 
 docker-push-%:
@@ -105,6 +105,13 @@ docker-push-%:
 	@echo "---End Docker Push for $*---"
 
 docker-push: $(addprefix docker-push-,$(DOCKER_TARGETS))
+
+helm-build:
+	@echo "This is a dummy helm-build target."
+
+helm-push:
+	@echo "This is a dummy helm-push target."
+
 clean:
 	@# Help: Runs clean stage in all subprojects
 	rm -rf k8s/
